apiVersion: v1
kind: Pod
metadata:
  name: secure-pod-no-hostpath
  namespace: audit-zone
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    volumeMounts:
    - name: empty-dir
      mountPath: /tmp
  volumes:
  - name: empty-dir
    emptyDir: {}
